runtime: nodejs
vm: true
module: default
threadsafe: true

resources:
  cpu: .5
  memory_gb: .5
  disk_size_gb: 10

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

handlers:
- url: /.*
  script: IGNORED
  secure: always